/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


//stesso progetto di prima ma al posto di utilizzare il registro di
//output ODR si utilizza il registro di set e reset BSRR
#include <stdint.h>
#include "stm32f4xx.h"
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/

#define GPIOG_EN (1U<<6)
#define PIN13 (1U<<13)
#define LED_PIN PIN13

#define GPIOA_EN (1U<<0)
#define PIN0 (1U<<0)
#define BTN_PIN PIN0
//button connected to PA0


void blink();

int main(void)
{
	RCC->AHB1ENR |= GPIOG_EN;
	RCC->AHB1ENR |= GPIOA_EN;

	GPIOG->MODER |= (1U<<26);
	GPIOG->MODER &=~(1U<<27);

	GPIOA->MODER &=~(1U<<0);
	GPIOA->MODER &=~(1U<<0);



	/* Loop forever */
	while(1)
	{

		if (GPIOA->IDR & BTN_PIN)
			blink();
			//GPIOG->BSRR = LED_PIN;

		//per accendere bisogna settare il bit set a 1
		//GPIOG->BSRR = LED_PIN;
		//for (int i=1; i<=1000000; i++) {}

		//per spegnere bisogna settare il bit reset a 1
		//else
			//GPIOG->BSRR = (1U<<29);

	}






}

void blink()
{
	for(int k=0; k<=5 ;k ++)
	{
	GPIOG->BSRR = LED_PIN;
	for (int i=1; i<=100000; i++) {}
	GPIOG->BSRR = (1U<<29);
	for (int i=1; i<=100000; i++) {}
	}
}

